//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("BizTalk Server Web Documenter")]
[assembly: AssemblyDescription("Documentation tool for BizTalk Server")]
[assembly: AssemblyProduct("btswebdoc")]
[assembly: AssemblyCopyright("Copyright © Richard Hallgren with friends")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("B61E5938-E5AE-11E0-B163-ED314824019B")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.3.0.0")]
[assembly: AssemblyInformationalVersion("1.3.0.0")]


